name: yaplingo

services:
  server:
    image: yaplingo-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server/server
      - cache:/root/.cache
    depends_on:
      database:
        condition: service_healthy
      store:
        condition: service_healthy
    # models:
    #   - llm
    tty: true

  worker:
    image: yaplingo-server:latest
    pull_policy: never
    command:
      ["uv", "run", "taskiq", "worker", "server:broker", "--use-process-pool"]
    env_file: .env
    volumes:
      - ./server:/server/server
      - cache:/root/.cache
    depends_on:
      database:
        condition: service_healthy
      store:
        condition: service_healthy
    # models:
    #   - llm
    tty: true

  database:
    image: postgres:latest
    env_file: .env
    command: >
      -c min_wal_size=512MB
      -c max_wal_size=1GB
      -c wal_compression=on
      -c checkpoint_timeout=86400
    volumes:
      - postgres:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  store:
    image: redis:latest
    env_file: .env
    volumes:
      - redis:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s

volumes:
  postgres:
  redis:
  cache: # persist model cache between restarts

# models:
#   llm:
#     model: ai/llama3.1
#     runtime_flags:
#       - "--no-prefill-assistant"
